$(document).ready(function(){
	$('#save').click(function(){
		$('form').savr('save');
	});
	$('#load').click(function(){
		$('form').savr('load');
	});
	$('#clear').click(function(){
		$('form').savr('clear');
	});
	$('#exists').click(function(){
		console.log($('form').savr('exists'));
	});
	$('#start').click(function(){
		$('form').savr('start');
	});
	$('#stop').click(function(){
		$('form').savr('stop');
	});
	$('#is-default').click(function(){
		console.log($('form').savr('isDefault'));
	});
})